### ISSUE TITLE
Fault type

### ISSUE THREAD

**Issue by ydluo** [ydluo/qdyn#10]
Dear co-developer I noticed that the fault type (strike-slip, thrust, etc) is hard-coded as constant (in constants.f90), i.e. each time users of QDYN want to use a different fault type they will have to recompile the code (and it is not properly documented in the manual). Is there a good reason for doing so (e.g. computation efficiency, etc.)? If not we need to fix that as a run-time input.

Yingdi

**Comment by jpampuero** [comment]
I see no reason to leave it as a hard-coded parameter. As noted in my comment in the code: "this should be an input in qdyn.in, not a parameter here".
Pablo

**Comment by martijnende** [comment]
Same for the solver flag (Bulirsch-Stoer vs. Runge-Kutta). I was going to fix this over the next few days, I'll include the `FAULT_TYPE` as well.

**Comment by martijnende** [comment]
The user parameters `SOLVER` and `FAULT_TYPE`, as well as a dilatancy hardening coefficient (used in thermal pressurisation), are now written to `qdyn.in` by `qdyn.m` and/or `pyqdyn.py`.

**Comment by jpampuero** [comment]
Thanks for fixing that, Martijn. Can you document these new input variables in the user's manual?

**Comment by martijnende** [comment]
Done, and added CNS model parameters
