### ISSUE TITLE
Compatibility with older version of Matlab

### ISSUE THREAD

**Issue by ydluo** [ydluo/qdyn#11]
Dear co-developers I recently experienced some minor and confusion issues while running the current version of QDYN (R518) with older version of Matlab. The code runs properly but there is no screen output of any kind in Matlab (also no warning / error message). Everything is fine with newer version of Matlab though (Matlab 9.0 +). 
Does anyone experience similar issue here? It does not impact the functionality of the code (can check the progress in fort.*) but it's just annoying.

YD

**Comment by martijnende** [comment]
I never use Matlab, so I can't verify this issue. Do earlier commits reproduce this issue?

**Comment by ydluo** [comment]
OK seems that's just a issue of how Matlab defaults output device, 
We might want to replace write(6,*) with write(*,*) for better compatibility.

**Comment by jpampuero** [comment]
There is no write(6,) in matlab code, so how is that related to matlab default output device? Also, the syntax is write(... , ...) with two arguments.
Can you explain accurately the origin of the issue? Or just fix it.

**Comment by martijnende** [comment]
Any updates on the status of this issue? Is it still relevant, or can I close it?
