### ISSUE TITLE
There are some difference between the results calculated by serial code and parallel code

### ISSUE THREAD

**Issue by yayadian2012** [ydluo/qdyn#18]
Dear QDYN developer,

I'm a newer in dynamic simulation. I feel very appricate for you to share the QDYN soft.
I find the results calculated by serial code and parallel code are not identical. Such as "JP_2d_s.m",  the Vmax~time relation are extremely different when NPROCS=1,3,4. The same issue also existed in other examples, such as JP_3d.m, JP_3d_l.m.

The fortran compiler is gfortran, with only MPI no openMP.

Looking forward for your reply. Thank you very much!

**Comment by martijnende** [comment]
Hello Yayadian, thanks for reporting this (rather critical) issue. @ydluo, @bidini: I'm currently without a suitable set-up for investigating this. Could one or both of you verify the issue by running one of the examples in parallel and serial? This could be important for the upcoming SEAS benchmark session.

**Comment by ydluo** [comment]
I have run serial and MPI parallel with "example/test3d_fft" in the past and find identical results, will re-run and look at the Japan 2D case.

**Comment by yayadian2012** [comment]
Hello Martijn van den Ende and ydluo, thanks for your prompt reply. I'll be waiting for your googd news.

**Comment by yayadian2012** [comment]
The problem is solved plausibly.

**Comment by martijnende** [comment]
I don't think the problem has been reproduced and/or solved yet. We are currently comparing the results with benchmarks, which may expose the issue you reported. Stay tuned.

**Comment by yayadian2012** [comment]
Hi, martijnende, I'm very glad to hear from you.  Thank you very much!

**Comment by martijnende** [comment]
In the latest releases of QDYN, there are numerous issues with the parallel code execution, which will need to be revised. Any differences between parallel and serial execution will be addressed when we revamp the parallel modules. If this problem persists after revision of the parallel code, this issue can be reopened.
