### ISSUE TITLE
FFT of vector of arbitrary size

### ISSUE THREAD

**Issue by martijnende** [ydluo/qdyn#21]
As @gpercy and @jpampuero mentioned to me, the current FFT routine requires a vector of size `2^N`, though there are no internal checks for this requirement, possibly resulting in corrupt/inaccurate data. Possible workarounds:

1. Add a sanity check while the input file is being read, to make sure that the mesh size is a power of 2
2. Allow for arbitrary mesh sizes, but pad the data vector with zeros

The latter is more user-friendly, while the former is computationally more efficient.

**Comment by jpampuero** [comment]
I implemented option 1 in the matlab wrapper, only for MESHDIM=1.
For MESHDIM=2, this needs to be done in the fortran code. 
I also modified the user's manual (the google doc) accordingly.

**Comment by jpampuero** [comment]
I implemented option 1 also in the fortran code.
Option 2 does not work with our periodic kernels expressed analytically in spectral domain (wavenumber). Hence we can close this issue.

**Comment by jpampuero** [comment]
1. I modified the code to execute the power-of-2 test only when fft is (re)initialized. Usually this happens only once during a run. Keeping the test in the fft module satisfies the encapsulation principle, but feel free to implement an additional test in the initiation stage.
2. The is-a-power-of-2 test can be implemented in one line using a bit manipulation trick with intrinsic functions in Fortran 2008 as `n>1 .and. popcnt(n)==1`. If you implement that, please keep also the other version of the test in case some users don't have a Fortran 2008 compiler (I have seen this happen in other software projects).

**Comment by martijnende** [comment]
All right, I think Pablo's implementation is satisfactory, so I'll close this issue now.
