### ISSUE TITLE
Several asperities

### ISSUE THREAD

**Issue by Polyatykin** [ydluo/qdyn#64]
Dear developers,
  how could I set up several asperities ?

**Comment by jpampuero** [comment]
You can set asperities by creating a spatial distribution of A and B such that some areas have A-B<0 (asperities) and the rest of the fault has A-B>0. If you want the asperities to produce seismic slip, you should set their size larger than their nucleation size (given in equation 42 of Rubin & Ampuero 2005 https://doi.org/10.1029/2005JB003686).
We provide an example with one asperity (examples/single_asperity) and another with two asperities (examples/double_asperities).
