### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [ydluo/qdyn#68]
I suggest adding topics such as `earthquakes`, `seismology`, `geophysics` in the About section at https://github.com/ydluo/qdyn.

**Comment by martijnende** [comment]
Thanks for your suggestion. When I look at the About section, I see exactly these topics being displayed. Perhaps @jpampuero added these already?

**Comment by jpampuero** [comment]
It was updated by @ydluo upon my request. He is the only one who can edit that section.
