### ISSUE TITLE
Would you like to help me?

### ISSUE THREAD

**Issue by xubeigithub** [ydluo/qdyn#7]
I am a novice in the dynamic earthquake simulation. I have read some papers about this respect, but I find that reading and writing code maybe more important than reading papers. It is very lucky that I find the qdyn program, and I am curious about are there any other freely available code about dynamic earthquake simulation. I do not mean that the qdyn program is not good, to the opposite, it gives me a lot of help. I just want to learn more about the dynamic earthquake simulation. Would you like to give me some help or advices?

**Comment by jpampuero** [comment]
I have developed a number of codes for rupture dynamics through the years. They are listed here: http://web.gps.caltech.edu/~ampuero/software.html

SEM2DPACK (https://sourceforge.net/projects/sem2d/) and SEMLAB (https://nl.mathworks.com/matlabcentral/fileexchange/6154-semlab) are 2D dynamic earthquake rupture and wave propagation simulators developed. My team also developed 3D earthquake dynamic simulation modules in SPECFEM3D (https://geodynamics.org/cig/software/specfem3d/). All these are based on the spectral element method.
I have also developed a 2D dynamic rupture code based on the spectral boundary integral method, BIMAT-PCSI (http://web.gps.caltech.edu/~ampuero/soft/bimat_1.1.2.tar.gz) and a matlab version SBIEMLAB (http://web.gps.caltech.edu/~ampuero/soft/SBIEMLAB_0.1.tar.gz).
JP Ampuero

**Comment by xubeigithub** [comment]
Thank you very much for your help!
