### ISSUE TITLE
Following the issue #79

### ISSUE THREAD

**Issue by bowenyu1** [ydluo/qdyn#80]
Dear Dr. Martijn van de Ende

These days I am attempting to incorporating a "new" friction law into QDYN that takes into account the regularized RSF law, flash heating, and the effects of mechanical work on weakening temperature _Tw_ (see the equation set in the attached figure). The most difficult aspect of this approach was adding the differential equation "dmw/dt = _tau_ * _v_" in order to calculate the real-time mechanical work _mw_ and then _Tw_. In my modified version, the treatment of _mw_ is identical to your treatment of the state variable theta. Could you tell me whether this implementation is correct?

I have successfully compiled the modified code, but an error titled <Program received signal SIGABRT: Process abort signal. Backtrace for this error: Could nor print backtrace: executable file is not an executable...> occurs when I attempt to run the Single asperity (2D) tetorial code in python. The progression may halt at `p.run()`. I have tried to debug this in numerous ways, but have always failed. I would appreciate your assistance with that.

I have uploaded the updated filed assiciated with this issue. For your convenience, I have also categorized the positions I have made changes, as shown below:

1. In friction. f90: line18, 41-43, 78-79, 94-104, 113-114, 138-148
2. In problem_class. f90: line132 (neqs 3=>4), 117-118, 129-130, 151
3. In derivs_all. f90: line29, 38, 55, 99, 156
4. In solver. f90: line86, 161, 296
5. In utils. f90: line25, 29, 44, 59, 63, 76
6. In unittests_rsf. f90: line37, 95, 106
7. In unittests. f90: line171, 175. 188
8. In output. f90: line57, 93, 116, 372, 456, 458, 989
9. In input. f90: line58, 158
10. In pyqdyn. py: line114-119, 254, 432

Thanks for your time!

Bowen
<img width="624" alt="rsf+fh law (bowen)" src="https://user-images.githubusercontent.com/128716664/227987925-295ebacd-eba6-4145-9e1f-52e78a8a9c21.png">
[modified src(bowen).zip](https://github.com/ydluo/qdyn/files/11080372/modified.src.bowen.zip)

_Originally posted by @bowenyu1 in https://github.com/ydluo/qdyn/issues/79#issuecomment-1485341723_

**Comment by martijnende** [comment]
Closed as this conversation was continued in #79
